# Generated by Django 3.2.15 on 2022-09-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='album',
        ),
    ]
