# Generated by Django 3.2.15 on 2022-09-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image_filter',
        ),
    ]
